import smtplib
import os

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

from config import Config
from models.approval import ApprovalHistory
from services.pdf_service import generate_approval_report
from flask import current_app


def send_test_email():

    msg = MIMEText(
        "This is a test email from Document Approval System."
    )

    msg["Subject"] = "Test Email"
    msg["From"] = Config.MAIL_DEFAULT_SENDER
    msg["To"] = Config.ACCOUNTING_EMAIL

    print("MAIL_SERVER =", Config.MAIL_SERVER)
    print("MAIL_PORT =", Config.MAIL_PORT)
    print("MAIL_USERNAME =", Config.MAIL_USERNAME)
    print("MAIL_PASSWORD =", bool(Config.MAIL_PASSWORD))

    with smtplib.SMTP(
        Config.MAIL_SERVER,
        Config.MAIL_PORT,
    ) as server:

        server.starttls()

        server.login(
            Config.MAIL_USERNAME,
            Config.MAIL_PASSWORD
        )

        server.send_message(msg)

    print("Email sent successfully.")

def send_approval_email(document):

    pdf_path = generate_approval_report(document)
    history = ApprovalHistory.query.filter_by(
        document_id=document.id
    ).all()

    rows = ""

    for item in history:

        rows += f"""
        <tr>
            <td style="padding:10px;border:1px solid #ddd;">
                {item.approver}
            </td>

            <td style="padding:10px;border:1px solid #ddd;text-align:center;">
                {item.action}
            </td>

            <td style="padding:10px;border:1px solid #ddd;">
                {item.approved_at.strftime('%d/%m/%Y %H:%M')}
            </td>

            <td style="padding:10px;border:1px solid #ddd;">
                {item.comment if item.comment else '-'}
            </td>

        </tr>
        """

    html = f"""
<html>

<body style="font-family:Arial;background:#f4f4f4;padding:30px;">

<div style="
max-width:900px;
margin:auto;
background:white;
padding:30px;
border-radius:10px;
box-shadow:0 0 10px rgba(0,0,0,.15);
">

<h2 style="color:#0d6efd;">
📄 Document Approval Notification
</h2>

<p>
The following document has been fully approved.
</p>

<h3>Document Information</h3>

<table style="
width:100%;
border-collapse:collapse;
">

<tr>
<th style="background:#0d6efd;color:white;padding:10px;border:1px solid #ddd;">
Document No
</th>

<td style="padding:10px;border:1px solid #ddd;">
{document.document_no}
</td>
</tr>

<tr>
<th style="background:#0d6efd;color:white;padding:10px;border:1px solid #ddd;">
Document Type
</th>

<td style="padding:10px;border:1px solid #ddd;">
{document.document_type}
</td>
</tr>

<tr>
<th style="background:#0d6efd;color:white;padding:10px;border:1px solid #ddd;">
Title
</th>

<td style="padding:10px;border:1px solid #ddd;">
{document.title}
</td>
</tr>

<tr>
<th style="background:#0d6efd;color:white;padding:10px;border:1px solid #ddd;">
Created By
</th>

<td style="padding:10px;border:1px solid #ddd;">
{document.created_by}
</td>
</tr>

<tr>
<th style="background:#0d6efd;color:white;padding:10px;border:1px solid #ddd;">
Status
</th>

<td style="
padding:10px;
border:1px solid #ddd;
color:green;
font-weight:bold;
">
Approved
</td>
</tr>

</table>

<br>

<h3>Approval History</h3>

<table style="
width:100%;
border-collapse:collapse;
">

<tr style="background:#198754;color:white;">

<th style="padding:10px;border:1px solid #ddd;">
Approver
</th>

<th style="padding:10px;border:1px solid #ddd;">
Action
</th>

<th style="padding:10px;border:1px solid #ddd;">
Date
</th>

<th style="padding:10px;border:1px solid #ddd;">
Comment
</th>

</tr>

{rows}

</table>

<br>

<p>
Please proceed with the next process.
</p>

<hr>

<p style="color:gray;font-size:12px;">

This email was automatically generated by

<b>Document Approval System</b>

</p>

</div>

</body>

</html>
"""

    msg = MIMEMultipart()

    msg.attach(MIMEText(html, "html"))

    msg["Subject"] = f"Document Approved : {document.document_no}"

    msg["From"] = Config.MAIL_DEFAULT_SENDER

    msg["To"] = Config.ACCOUNTING_EMAIL

    if os.path.exists(pdf_path):

        with open(pdf_path, "rb") as pdf_file:

            attachment = MIMEBase(
                "application",
                "octet-stream"
            )

            attachment.set_payload(
                pdf_file.read()
            )

        encoders.encode_base64(attachment)

        attachment.add_header(

            "Content-Disposition",

            f'attachment; filename="{os.path.basename(pdf_path)}"'

        )

        msg.attach(attachment)

        original_file = os.path.join(
            current_app.config["UPLOAD_FOLDER"],
            document.file_name
        )

        if os.path.exists(original_file):

            with open(original_file, "rb") as file:

                original_attachment = MIMEBase(
                    "application",
                    "octet-stream"
                )

                original_attachment.set_payload(
                    file.read()
                )

            encoders.encode_base64(original_attachment)

            original_attachment.add_header(
                "Content-Disposition",
                f'attachment; filename="{document.file_name}"'
            )

            msg.attach(original_attachment)

    print("EMAIL SKIPPED")

    print("Approval email sent successfully.")