import os


from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)

from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime

from models.approval import ApprovalHistory

def generate_approval_report(document):
    pdfmetrics.registerFont(

        TTFont(

            "Sarabun",

            "fonts/Sarabun-Regular.ttf"

        )

    )

    styles = getSampleStyleSheet()

    styles["Title"].fontName = "Sarabun"

    styles["Heading2"].fontName = "Sarabun"

    styles["BodyText"].fontName = "Sarabun"

    folder = "uploads/reports"

    os.makedirs(folder, exist_ok=True)

    filename = f"Approval_Report_{document.document_no}.pdf"

    filepath = os.path.join(folder, filename)

    doc = SimpleDocTemplate(filepath)

    elements = []

    logo = Image(
        "static/images/leo_logo.png",
        width=180,
        height=78
    )

    elements.append(logo)

    elements.append(Spacer(1,15))

    elements.append(

    Paragraph(
            "<b>DOCUMENT APPROVAL REPORT</b>",
            styles["Title"]
        )

    )

    elements.append(Spacer(1,20))

    data = [

        ["Document No", document.document_no],

        ["Document Type", document.document_type],

        ["Title", document.title],

        ["Created By", document.created_by],

        ["Status", document.status],

        ["Generated Date",

        datetime.now().strftime("%d/%m/%Y %H:%M")]

    ]

    table = Table(data)

    table.setStyle(

        TableStyle([

            ("FONTNAME",(0,0),(-1,-1),"Sarabun"),

            ("BACKGROUND",(0,0),(0,-1),colors.lightblue),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),8),

        ])

    )

    elements.append(table)

    elements.append(Spacer(1,20))

    history = ApprovalHistory.query.filter_by(
        document_id=document.id
    ).all()

    elements.append(

    Paragraph(
            "<b>Approval History</b>",
            styles["Heading2"]
        )

    )

    elements.append(Spacer(1,10))

    history_data = [

        [

            "No.",

            "Approver",

            "Action",

            "Date",

            "Comment"

        ]

    ]

    for index, item in enumerate(history, start=1):

        history_data.append(

            [

                index,

                item.approver,

                item.action,

                item.approved_at.strftime("%d/%m/%Y %H:%M"),

                item.comment if item.comment else "-"

            ]
        )

    history_table = Table(

        history_data,

        colWidths=[40,110,80,120,170]

    )

    history_table.setStyle(

        TableStyle([

            ("FONTNAME",(0,0),(-1,-1),"Sarabun"),

            ("BACKGROUND",(0,0),(-1,0),colors.green),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),8),

        ])

    )

    elements.append(history_table)

    elements.append(Spacer(1,25))

    elements.append(

        Paragraph(

            "Generated by <b>Document Approval System</b>",

            styles["BodyText"]

        )

    )

    doc.build(elements)

    return filepath